import type { DailyArticle } from './types'

export const sampleArticle: DailyArticle = {
  id: 'daily-en-2026-05-24-breathing-room',
  contentVersion: '2026-05-24.0',
  language: 'en',
  level: 'B1',
  topic: 'knowledge',
  title: 'The Quiet Power of a Short Walk',
  deck: 'A five-minute English practice article about attention, movement, and recovery.',
  estimatedReadTimeMinutes: 5,
  factSources: [
    {
      title: 'WHO physical activity fact sheet',
      url: 'https://www.who.int/news-room/fact-sheets/detail/physical-activity',
    },
  ],
  rights: {
    sourceType: 'ai-generated',
    rightsStatus: 'owned',
    licenseNote: 'Generated for Yomu V0 spike; no third-party article text.',
    ttsAllowed: true,
    translationAllowed: true,
    cacheAllowed: true,
  },
  model: {
    provider: 'fixture',
    name: 'human-authored-fixture',
    version: 'v0',
    promptHash: 'fixture-only',
  },
  qaStatus: 'approved',
  sentences: [
    {
      id: 's1',
      original: 'A short walk can change the shape of a difficult afternoon.',
      translation: '一次短短的散步,可以改变一个艰难下午的状态。',
      tokens: [
        { text: 'A', ipa: 'ə', kind: 'word' },
        { text: 'short', ipa: 'ʃɔːrt', kind: 'word' },
        { text: 'walk', ipa: 'wɔːk', kind: 'word' },
        { text: 'can', ipa: 'kæn', kind: 'word' },
        { text: 'change', ipa: 'tʃeɪndʒ', kind: 'word' },
        { text: 'the', ipa: 'ðə', kind: 'word' },
        { text: 'shape', ipa: 'ʃeɪp', kind: 'word' },
        { text: 'of', ipa: 'əv', kind: 'word' },
        { text: 'a', ipa: 'ə', kind: 'word' },
        { text: 'difficult', ipa: 'ˈdɪfɪkəlt', kind: 'word' },
        { text: 'afternoon', ipa: 'ˌæftərˈnuːn', kind: 'word' },
        { text: '.', kind: 'punctuation' },
      ],
      audioRef: { id: 'audio-s1', url: 'fixture://audio/s1', durationMs: 1200 },
      vocab: [{ term: 'shape', meaning: '状态、形态;这里指体验的整体感觉' }],
    },
    {
      id: 's2',
      original: 'Your eyes leave the screen, and your breathing becomes easier.',
      translation: '你的眼睛离开屏幕,呼吸也会变得更轻松。',
      tokens: [
        { text: 'Your', ipa: 'jʊr', kind: 'word' },
        { text: 'eyes', ipa: 'aɪz', kind: 'word' },
        { text: 'leave', ipa: 'liːv', kind: 'word' },
        { text: 'the', ipa: 'ðə', kind: 'word' },
        { text: 'screen', ipa: 'skriːn', kind: 'word' },
        { text: ',', kind: 'punctuation' },
        { text: 'and', ipa: 'ænd', kind: 'word' },
        { text: 'your', ipa: 'jʊr', kind: 'word' },
        { text: 'breathing', ipa: 'ˈbriːðɪŋ', kind: 'word' },
        { text: 'becomes', ipa: 'bɪˈkʌmz', kind: 'word' },
        { text: 'easier', ipa: 'ˈiːziər', kind: 'word' },
        { text: '.', kind: 'punctuation' },
      ],
      audioRef: { id: 'audio-s2', url: 'fixture://audio/s2', durationMs: 1200 },
    },
    {
      id: 's3',
      original: 'The goal is not exercise; it is a small reset.',
      translation: '目标不一定是锻炼,而是一次小小的重置。',
      tokens: [
        { text: 'The', ipa: 'ðə', kind: 'word' },
        { text: 'goal', ipa: 'ɡoʊl', kind: 'word' },
        { text: 'is', ipa: 'ɪz', kind: 'word' },
        { text: 'not', ipa: 'nɑːt', kind: 'word' },
        { text: 'exercise', ipa: 'ˈeksərsaɪz', kind: 'word' },
        { text: ';', kind: 'punctuation' },
        { text: 'it', ipa: 'ɪt', kind: 'word' },
        { text: 'is', ipa: 'ɪz', kind: 'word' },
        { text: 'a', ipa: 'ə', kind: 'word' },
        { text: 'small', ipa: 'smɔːl', kind: 'word' },
        { text: 'reset', ipa: 'ˌriːˈset', kind: 'word' },
        { text: '.', kind: 'punctuation' },
      ],
      audioRef: { id: 'audio-s3', url: 'fixture://audio/s3', durationMs: 1200 },
    },
  ],
}
