/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 5c8279f77c21b26e267bfb0d0eddf757)
interface __BaseEnv_Env {
	URL_IMPORT_RATE_LIMITER: RateLimit;
	MIMO_TTS_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	MIMO_TTS_MODEL: "mimo-v2.5-tts";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MIMO_TTS_MODEL">> {}
}
